import { NextResponse } from "next/server";
import axios from "axios";

export async function POST(req) {
  try {
    const { text } = await req.json();
    if (!text) {
      return NextResponse.json({ error: "Text is required" }, { status: 400 });
    }

    // Call OpenAI's GPT API
    const response = await axios.post(
      "https://api.openai.com/v1/chat/completions",
      {
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: `
                # Instructions:
                You are a grammar correction assistant very similar to the service grammarly. I'll give you sentences and your role will be to spot the grammar errors compared to regular english and return the errors in a JSON format. If there is no errors then return \`null\`

                # Output Format:
                {
                  "correctText": "Corrected sentence",
                  "errors": [
                    { "word": "incorrectWord", "index": wordIndex, "correctWord": "correctWord" }
                  ],
                  "text": "Original input text"
                }

                # Requirements:
                1. The \`index\` of each word must match its position in the array generated by \`string.split(" ")\` (splitting by spaces).
                2. The sentence should be split based on spaces to determine word positions accurately.

                # Example:
                **Input:** "I don't want to got to school today"

                **Expected Response:**
                {
                  "correctText": "I don't want to go to school today",
                  "errors": [
                    { "word": "got", "index": 4, "correctWord": "go" }
                  ],
                  "text": "I don't want to got to school today"
                }

                # Input:
                "${text}"
                `,
          },
        ],
        temperature: 0,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
          "Content-Type": "application/json",
        },
      }
    );

    // Parse OpenAI's response
    const structuredResponse = JSON.parse(
      response.data.choices[0].message.content
    );
    // console.log(structuredResponse, "api response");

    return NextResponse.json({ ...structuredResponse });
  } catch (error) {
    console.error("Error calling OpenAI API:", error);
    return NextResponse.json(
      { error: "Failed to correct text" },
      { status: 500 }
    );
  }
}
